import = ["/home/kasrkad/.config/alacritty/dracula/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[window]
opacity = 0.8
startup_mode = "Maximized"
blur = true
title = "MegaTerm"
[selection]
save_to_clipboard = true
[cursor]
style = { shape = "Block", blinking = "Always"}

